[package]
edition = "2021"
name    = "watchy-m5"
version = "0.1.0"

[[bin]]
name = "watchy-m5"
path = "./src/bin/main.rs"

[dependencies]
defmt = "1.0.1"
embassy-net = { version = "0.7.0", features = [
  "dhcpv4",
  "medium-ethernet",
  "tcp",
  "udp",
] }
embedded-io = "0.6.1"
embedded-io-async = "0.6.1"
esp-alloc = "0.8.0"
esp-backtrace = { version = "0.16.0", features = [
  "defmt",
  "esp32",
  "exception-handler",
  "panic-handler",
] }
esp-hal = { version = "1.0.0-beta.1", features = [
  "defmt",
  "esp32",
  "unstable",
  "psram",
] }
esp-println = { version = "0.14.0", features = ["defmt-espflash", "esp32"] }
smoltcp = { version = "0.12.0", default-features = false, features = [
  "medium-ethernet",
  "multicast",
  "proto-dhcpv4",
  "proto-dns",
  "proto-ipv4",
  "socket-dns",
  "socket-icmp",
  "socket-raw",
  "socket-tcp",
  "socket-udp",
] }
# for more networking protocol support see https://crates.io/crates/edge-net
bleps = { git = "https://github.com/bjoernQ/bleps", package = "bleps", rev = "a5148d8ae679e021b78f53fd33afb8bb35d0b62e", features = [
  "async",
  "macros",
] }
critical-section = "1.2.0"
embassy-executor = { version = "0.7.0", features = [
  "defmt",
  "task-arena-size-20480",
] }
embassy-time = { version = "0.4.0", features = ["generic-queue-8"] }
esp-hal-embassy = { version = "0.8.0", features = ["esp32"] }
esp-wifi = { version = "0.14.0", features = [
  "ble",
  "builtin-scheduler",
  "coex",
  "defmt",
  "esp-alloc",
  "esp32",
  "wifi",
] }

heapless = { version = "0.8.0", default-features = false }
static_cell = { version = "2.1.0", features = ["nightly"] }
mipidsi = "0.9.0"
embedded-graphics = { version = "0.8.1", features = ["defmt"] }
axp192 = "0.2.0"
display-interface-spi = "0.5.0"
# embedded-hal = { version = "1.0.0", features = ["defmt-03"] }
# embassy-embedded-hal = { version = "0.3.0", features = ["defmt"] }
# embassy-sync = { version = "0.7.0", features = ["defmt"] }
embedded-hal-bus = { version = "0.3.0", features = ["defmt-03", "async"] }
pcf8563 = "0.1.0"
mpu6886 = "0.1.0"
embassy-sync = { version = "0.7.0", features = ["defmt"] }


[patch.crates-io]
esp-hal = { git = "https://github.com/esp-rs/esp-hal", rev = "75f728aec9018e290d33910dde45b32bfe55b86f" } 
esp-wifi = { git = "https://github.com/esp-rs/esp-hal", rev = "75f728aec9018e290d33910dde45b32bfe55b86f" } 
esp-alloc = { git = "https://github.com/esp-rs/esp-hal", rev = "75f728aec9018e290d33910dde45b32bfe55b86f" }
pcf8563 = { git = "https://github.com/hyx0329/pcf8563-rs", rev = "0c78da51d5fb429fd3c447103432a7de66cf1bed" }
mpu6886 = { git = "https://github.com/hyx0329/mpu6886-rs", rev = "0a3f8860f9e0ad5b0b6e2d600edb67de20a91fa6" }


[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.dev.package.esp-wifi]
opt-level = 3

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false
