[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32 --log-format defmt"

[env]
DEFMT_LOG="info"
ESP_WIFI_CONFIG_STATIC_RX_BUF_NUM="5"
ESP_WIFI_CONFIG_DYNAMIC_RX_BUF_NUM="16"
ESP_WIFI_CONFIG_DYNAMIC_TX_BUF_NUM="16"
ESP_WIFI_CONFIG_COUNTRY_CODE="US"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Wl,-Map=output.map",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
