use crate::music::*;

// change this to make the song slower or faster
pub const TEMPO: u16 = 120;

// Pink Panther theme
// Score available at https://musescore.com/benedictsong/the-pink-panther
// Theme by Masato Nakamura, arranged by Teddy Mason
// pub const MELODY: [(f64, i16); 88] = [
pub const MELODY: [MusicNote; 88] = [
    MusicNote::Rest(2),
    MusicNote::Rest(4),
    MusicNote::Rest(8),
    MusicNote::Sound(NOTE_DS4, 8),
    MusicNote::Sound(NOTE_E4, -4),
    MusicNote::Rest(8),
    MusicNote::Sound(NOTE_FS4, 8),
    MusicNote::Sound(NOTE_G4, -4),
    MusicNote::Rest(8),
    MusicNote::Sound(NOTE_DS4, 8),
    MusicNote::Sound(NOTE_E4, -8),
    MusicNote::Sound(NOTE_FS4, 8),
    MusicNote::Sound(NOTE_G4, -8),
    MusicNote::Sound(NOTE_C5, 8),
    MusicNote::Sound(NOTE_B4, -8),
    MusicNote::Sound(NOTE_E4, 8),
    MusicNote::Sound(NOTE_G4, -8),
    MusicNote::Sound(NOTE_B4, 8),
    MusicNote::Sound(NOTE_AS4, 2),
    MusicNote::Sound(NOTE_A4, -16),
    MusicNote::Sound(NOTE_G4, -16),
    MusicNote::Sound(NOTE_E4, -16),
    MusicNote::Sound(NOTE_D4, -16),
    MusicNote::Sound(NOTE_E4, 2),
    MusicNote::Rest(4),
    MusicNote::Rest(8),
    MusicNote::Sound(NOTE_DS4, 4),
    MusicNote::Sound(NOTE_E4, -4),
    MusicNote::Rest(8),
    MusicNote::Sound(NOTE_FS4, 8),
    MusicNote::Sound(NOTE_G4, -4),
    MusicNote::Rest(8),
    MusicNote::Sound(NOTE_DS4, 8),
    MusicNote::Sound(NOTE_E4, -8),
    MusicNote::Sound(NOTE_FS4, 8),
    MusicNote::Sound(NOTE_G4, -8),
    MusicNote::Sound(NOTE_C5, 8),
    MusicNote::Sound(NOTE_B4, -8),
    MusicNote::Sound(NOTE_G4, 8),
    MusicNote::Sound(NOTE_B4, -8),
    MusicNote::Sound(NOTE_E5, 8),
    MusicNote::Sound(NOTE_DS5, 1),
    MusicNote::Sound(NOTE_D5, 2),
    MusicNote::Rest(4),
    MusicNote::Rest(8),
    MusicNote::Sound(NOTE_DS4, 8),
    MusicNote::Sound(NOTE_E4, -4),
    MusicNote::Rest(8),
    MusicNote::Sound(NOTE_FS4, 8),
    MusicNote::Sound(NOTE_G4, -4),
    MusicNote::Rest(8),
    MusicNote::Sound(NOTE_DS4, 8),
    MusicNote::Sound(NOTE_E4, -8),
    MusicNote::Sound(NOTE_FS4, 8),
    MusicNote::Sound(NOTE_G4, -8),
    MusicNote::Sound(NOTE_C5, 8),
    MusicNote::Sound(NOTE_B4, -8),
    MusicNote::Sound(NOTE_E4, 8),
    MusicNote::Sound(NOTE_G4, -8),
    MusicNote::Sound(NOTE_B4, 8),
    MusicNote::Sound(NOTE_AS4, 2),
    MusicNote::Sound(NOTE_A4, -16),
    MusicNote::Sound(NOTE_G4, -16),
    MusicNote::Sound(NOTE_E4, -16),
    MusicNote::Sound(NOTE_D4, -16),
    MusicNote::Sound(NOTE_E4, -4),
    MusicNote::Rest(4),
    MusicNote::Rest(4),
    MusicNote::Sound(NOTE_E5, -8),
    MusicNote::Sound(NOTE_D5, 8),
    MusicNote::Sound(NOTE_B4, -8),
    MusicNote::Sound(NOTE_A4, 8),
    MusicNote::Sound(NOTE_G4, -8),
    MusicNote::Sound(NOTE_E4, -8),
    MusicNote::Sound(NOTE_AS4, 16),
    MusicNote::Sound(NOTE_A4, -8),
    MusicNote::Sound(NOTE_AS4, 16),
    MusicNote::Sound(NOTE_A4, -8),
    MusicNote::Sound(NOTE_AS4, 16),
    MusicNote::Sound(NOTE_A4, -8),
    MusicNote::Sound(NOTE_AS4, 16),
    MusicNote::Sound(NOTE_A4, -8),
    MusicNote::Sound(NOTE_G4, -16),
    MusicNote::Sound(NOTE_E4, -16),
    MusicNote::Sound(NOTE_D4, -16),
    MusicNote::Sound(NOTE_E4, 16),
    MusicNote::Sound(NOTE_E4, 16),
    MusicNote::Sound(NOTE_E4, 2),
];
