use crate::music::*;

// change this to make the song slower or faster
pub const TEMPO: u16 = 120;

// Pink Panther theme
// Score available at https://musescore.com/benedictsong/the-pink-panther
// Theme by Masato Nakamura, arranged by Teddy Mason
// pub const MELODY: [(f64, i16); 88] = [
pub const MELODY: [Note; 88] = [
    Note(REST, 2),
    Note(REST, 4),
    Note(REST, 8),
    Note(NOTE_DS4, 8),
    Note(NOTE_E4, -4),
    Note(REST, 8),
    Note(NOTE_FS4, 8),
    Note(NOTE_G4, -4),
    Note(REST, 8),
    Note(NOTE_DS4, 8),
    Note(NOTE_E4, -8),
    Note(NOTE_FS4, 8),
    Note(NOTE_G4, -8),
    Note(NOTE_C5, 8),
    Note(NOTE_B4, -8),
    Note(NOTE_E4, 8),
    Note(NOTE_G4, -8),
    Note(NOTE_B4, 8),
    Note(NOTE_AS4, 2),
    Note(NOTE_A4, -16),
    Note(NOTE_G4, -16),
    Note(NOTE_E4, -16),
    Note(NOTE_D4, -16),
    Note(NOTE_E4, 2),
    Note(REST, 4),
    Note(REST, 8),
    Note(NOTE_DS4, 4),
    Note(NOTE_E4, -4),
    Note(REST, 8),
    Note(NOTE_FS4, 8),
    Note(NOTE_G4, -4),
    Note(REST, 8),
    Note(NOTE_DS4, 8),
    Note(NOTE_E4, -8),
    Note(NOTE_FS4, 8),
    Note(NOTE_G4, -8),
    Note(NOTE_C5, 8),
    Note(NOTE_B4, -8),
    Note(NOTE_G4, 8),
    Note(NOTE_B4, -8),
    Note(NOTE_E5, 8),
    Note(NOTE_DS5, 1),
    Note(NOTE_D5, 2),
    Note(REST, 4),
    Note(REST, 8),
    Note(NOTE_DS4, 8),
    Note(NOTE_E4, -4),
    Note(REST, 8),
    Note(NOTE_FS4, 8),
    Note(NOTE_G4, -4),
    Note(REST, 8),
    Note(NOTE_DS4, 8),
    Note(NOTE_E4, -8),
    Note(NOTE_FS4, 8),
    Note(NOTE_G4, -8),
    Note(NOTE_C5, 8),
    Note(NOTE_B4, -8),
    Note(NOTE_E4, 8),
    Note(NOTE_G4, -8),
    Note(NOTE_B4, 8),
    Note(NOTE_AS4, 2),
    Note(NOTE_A4, -16),
    Note(NOTE_G4, -16),
    Note(NOTE_E4, -16),
    Note(NOTE_D4, -16),
    Note(NOTE_E4, -4),
    Note(REST, 4),
    Note(REST, 4),
    Note(NOTE_E5, -8),
    Note(NOTE_D5, 8),
    Note(NOTE_B4, -8),
    Note(NOTE_A4, 8),
    Note(NOTE_G4, -8),
    Note(NOTE_E4, -8),
    Note(NOTE_AS4, 16),
    Note(NOTE_A4, -8),
    Note(NOTE_AS4, 16),
    Note(NOTE_A4, -8),
    Note(NOTE_AS4, 16),
    Note(NOTE_A4, -8),
    Note(NOTE_AS4, 16),
    Note(NOTE_A4, -8),
    Note(NOTE_G4, -16),
    Note(NOTE_E4, -16),
    Note(NOTE_D4, -16),
    Note(NOTE_E4, 16),
    Note(NOTE_E4, 16),
    Note(NOTE_E4, 2),
];
